os: osx
before_install:
    - wget ftp://ftp.gnu.org/gnu/gsl/gsl-2.1.tar.gz
    - tar -zxf gsl-2.1.tar.gz
    - pushd gsl-2.1 && ./configure && make && make install && make clean && popd
    - curl -L https://cpanmin.us | perl - --sudo App::cpanminus
    - brew update mpfr
    - brew install parallel
    - wget http://abacus.gene.ucl.ac.uk/software/indelible/EFBKqHdv0v7qir6CyeHgqaz/INDELibleV1.03.tar.gz
    - wget https://www.niehs.nih.gov/research/resources/assets/docs/artsrcmountrainier20160605macostgz.tgz
    - git clone https://github.com/adamallo/SimPhy simphy
    - git clone https://github.com/merlyescalona/indelible-ngsphy
    - git clone https://github.com/merlyescalona/ngsphy
    - tar -zxf  artsrcmountrainier20160605macostgz.tgz
    - tar -zxf INDELibleV1.03.tar.gz
    - pushd simphy && make && make clean && popd
    - pushd INDELibleV1.03/src && rm MersenneTwister.h &&  wget https://raw.githubusercontent.com/merlyescalona/indelible-ngsphy/master/src/MersenneTwister.h && g++ -o indelible -O4 indelible.cpp  && popd
    - pushd art_src_MountRainier_MacOS/ && ./configure && make && popd
    - pushd indelible-ngsphy && make && popd
    - export PATH=$PATH:$(pwd)/simphy/bin
    - export PATH=$PATH:$(pwd)/INDELibleV1.03/src
    - export PATH=$PATH:$(pwd)/art_src_MountRainier_MacOS/
    - export PATH=$PATH:$(pwd)/indelible-ngsphy/bin
    - export PERL_MM_USE_DEFAULT=1
    - cpanm install Math::GSL
install:
    - pip install -r ngsphy/requirements.txt
    - python ngsphy/setup.py install
script:
    - ngsphy/test/ngsphy.all.tests.sh
